### PR TITLE
Should not replace + in phone numbers

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by rowanseymour** [comment]
The way this has been working is that we strip all punctuation, and then re-add a + prefix if what is left is the right length. I think this fix is fine but we should note that something like "1800+123+4567" would have previously normalised but now won't.

**Comment by norkans7** [comment]
I can change to support that too

**Comment by nicpottier** [comment]
That number is 11 digits, it should have the + added back in after stripping. Do the tests not pass without your change? Why not?

**Comment by norkans7** [comment]
https://github.com/nyaruka/gocommon/issues/3
 Yep It is phonenumbers which says this number is not valid

**Comment by norkans7** [comment]
@nicpottier @rowanseymour please review once again

**Comment by nicpottier** [comment]
This is not the right fix, you are passing back a '+' when we haven't validated the phone number.

This was an out of date database in phonenumbers. I've updated the DB, so if you update the vendored version of phonenumbers it should pass with no changes.

**Comment by norkans7** [comment]
I think this is still valid if we want to be consistent with the RapidPro behavior https://github.com/nyaruka/rapidpro/blob/master/temba/contacts/models.py#L244

**Pull request closed without merging**
