### PR TITLE
add weniwebchat urn

### PR DESCRIPTION
**Pull request by rasoro**
this new urn is needed for that PR nyaruka/courier#372 in Courier

### CODE REVIEW

**Comment by norkans7** [comment]
@rasoro how is the weniwebchat validated

can you add that as done on https://github.com/nyaruka/gocommon/pull/28/files ?

And tests as well

**Comment by rowanseymour** [comment]
Was chatting with @ericnewcomer about this yesterday and we think the way this would work is as follows:

- Users should be able to have an RP account that is connected to multiple Weni chat deployments on different websites. 
- The `weniwebchat` URN thus needs to include an identifier for each external site
- The external site itself should provide the chat client with a unique identifier for the current user and current site.

So say I'm running weni web chat on my "Foo" site, the client code needs to be initialized with 
 - user identifier which could be UUID associated with the currently authenticated user, or the current HTTP session if there isn't an authenticated user.
 - a identifier like `foo` for this site - just has to be unique across the sites I'm running Weni Web Chat on
 
When communicating with courier, the URN then should be something like `weniwebchat:123456@foo`, so that user `123456` on site `foo` can have multiple chats which map to the same contact in RP.

Could probably also let the scheme be generic like `webchat:123456@foo`.. even if we add different webchat channel types, they can still work from the same URN scheme.

**Comment by rasoro** [comment]
thank you very much for your tip, @norkans7 , it really helped me

**Comment by rasoro** [comment]
@rowanseymour, Thanks for the sugestion. We discussed it here on our side and we realized that it would really be a good approach if the urn could be used for any other webchat channel types.

**Comment by matmsa27** [comment]
URN updated on this [commit](https://github.com/nyaruka/rapidpro/pull/3488/commits/9de44026f8949ebe1c029d0aa28e331a35d430f7) on Rapidpro django

**Review by rowanseymour — APPROVED** [review]

**Pull request merged**
